version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  build:
    steps:
      - checkout
      - aws-s3/copy:
          arguments: '--dryrun'
          from: clickforaquote
          to: 'http://clickforaquote.s3-website-us-west-2.amazonaws.com'